Extract tag authorization in a dedicated service
steve-community/steve pull request #1005
Opened 2022-12-15 16:48 UTC by juherr

The objective of the change is to be able to delegate the authorization responsibility to an outside EMSP service if wanted.

WDYT?

2024-07-14 09:38 UTC, goekay commented
late feedback:

i think the goal is valuable. couple of suggestion from my side:

- can we do these without database changes?
- your changes are only encapsulating the auth part while leaving `OcppTagActivityRecord record = ocppTagRepository.getRecord(idTag);` as is. i would make this also part of the auth, because in such external cases the record does not necessarily have to be on local db.

2024-07-14 13:04 UTC, juherr commented
@goekay done as suggested

2024-07-14 13:54 UTC, goekay requested changes

2024-07-14 13:54 UTC, goekay commented on src/main/java/de/rwth/idsg/steve/service/AuthTagService.java
> +    OcppTagActivityRecord record = ocppTagRepository.getRecord(idTag);
the project uses 4-spaces indentation

note to self: we should enforce this by checkstyle.

2024-07-14 13:54 UTC, goekay commented on src/main/java/de/rwth/idsg/steve/service/OcppTagService.java
> +        @Nullable String chargeBoxId, @Nullable Integer connectorId) {
method parameter alignment after linebreak not consistent.

2024-07-14 13:54 UTC, goekay commented on src/main/java/de/rwth/idsg/steve/service/OcppTagService.java
> +                return idTagInfo;
we might question whether we need all the switch cases here (i think not). i guess we can just can use

```
if (idTagInfo.getStatus() == INVALID) {
    invalidOcppTagService.processNewUnidentified(idTag);
}

return idTagInfo
```

2024-07-14 13:54 UTC, goekay commented on src/main/java/de/rwth/idsg/steve/service/OcppTagService.java
> +        Supplier<IdTagInfo> supplierWhenException) {
method parameter alignment after linebreak not consistent.

2024-07-14 13:54 UTC, goekay commented on src/main/java/de/rwth/idsg/steve/utils/OcppTagActivityRecordUtils.java
> +  public static boolean isExpired(OcppTagActivityRecord record, DateTime now) {
the project uses 4-spaces indentation

2024-07-20 10:33 UTC, goekay commented
@juherr are you willing to do the changes or should i do them after merging?

2024-07-20 10:50 UTC, juherr commented
@goekay I'm currently in vacations and without a computer for the next 2 weeks.

You can wait or make the changed.
Fyi, you should be able to push on my branch and fix before the merge.

2024-07-20 11:23 UTC, goekay approved these changes

2024-07-20 11:55 UTC, merged

2024-07-20 11:55 UTC, goekay commented
thanks @juherr !

2024-07-20 12:11 UTC, juherr commented
@goekay thanks for the merge. Please review the other pull requests if you find some time